[tox]
no_package = true
skip_missing_interpreters = true
env_list = fmt, lint, unit

[vars]
src_path = {tox_root}/src
tst_path = {tox_root}/tests
lib_path = {tox_root}/lib

[testenv]
set_env =
    PYTHONPATH = {[vars]src_path}:{[vars]lib_path}
    PY_COLORS = 1
pass_env =
    PYTHONPATH
    HOME

[testenv:fmt]
description = Apply coding style standards.
deps =
    black
    isort
commands =
    isort {[vars]src_path} {[vars]tst_path}
    black {[vars]src_path} {[vars]tst_path}

[testenv:lint]
description = Lint the code.
deps =
    black
    isort
    ruff
commands =
    ruff check {[vars]src_path} {[vars]tst_path}
    black --check --diff {[vars]src_path} {[vars]tst_path}
    isort --check --diff {[vars]src_path} {[vars]tst_path}

[testenv:unit]
description = Run unit tests.
deps =
    -r {tox_root}/requirements.txt
    .[unit]
commands =
    coverage run --source={[vars]src_path} -m pytest -v --tb=native {posargs} {[vars]tst_path}/unit
    coverage report
